// src/routes/asset/[id]/+page.svelte
<script lang="ts">
import { bytesToFileSize } from '@/lib/helpers/asset/bytesToFileSize'
import { mapGame, mapAssetType } from '@/lib/helpers/casing/gameMapping'
import { getImageResolution } from '@/lib/helpers/asset/getImageResolution'
import { t } from 'svelte-i18n'
import { formatTimeAgo } from '@/lib/helpers/timeConvertion/isoFormat'
import { onMount } from 'svelte'
import AssetItem from '@/components/AssetItem.svelte'

let resolution = 'Unknown'
export let data

const { assetInformation, id } = data
const { asset, similarAssets } = assetInformation

// console.log(asset, similarAssets)

onMount(async () => {
    resolution = await getImageResolution(asset.url)
})

// console.log(assetInformation)
</script>

<svelte:head>
    <title>{asset.name} ({mapGame(asset.game)})</title>
</svelte:head>

<div class="min-h-screen">
    <div class="mb-8">
        <div class="px-2 md:px-12 lg:px-48">
            <div class="relative my-16">
                <div>
                    <div class="flex flex-col md:flex-row">
                        <div class="w-full md:w-1/2">
                            <img
                                src="{asset.url}"
                                alt="asset"
                                class="h-full max-h-full w-full max-w-full rounded-lg border border-main-300 bg-main-500 object-cover"
                                
                                style="background-image: url('/img/grid.png')" />
                        </div>
                        <div class="m-2 my-auto w-full md:w-1/2">
                            <div class="flex flex-col">
                                <div
                                    class="flex flex-col md:flex-row md:justify-between">
                                    <div class="flex flex-col">
                                        <div
                                            class="my-1 flex flex-row gap-2 text-lg">
                                                <a
                                                    href="/?game={asset.game}"
                                                    class="border-2 border-main-400 rounded-md bg-main-500 flex items-center px-2.5 py-1 font-semibold text-white transition duration-150 ease-in-out hover:-translate-y-1 hover:border-main-300">
                                                    <img
                                                        src="https://cdn.wanderer.moe/{asset.game}/icon.png"
                                                        alt="{asset.game} cover"
                                                        class="mr-1 inline-block h-5 w-5 rounded-md" />
                                                    {mapGame(asset.game)}
                                                </a>
                                                <a
                                                    href="/?asset={asset.asset}"
                                                    class="border-2 border-main-400 rounded-md bg-main-500 px-2.5 py-1 font-semibold text-white transition duration-150 ease-in-out hover:-translate-y-1 hover:border-main-300">
                                                    {mapAssetType(asset.asset)}
                                                </a>
                                        </div>
                                        <div class="my-2">
                                            <h1
                                                class="text-3xl font-bold text-white">
                                                {asset.name}
                                            </h1>
                                            <p class="text-sm text-gray-300">
                                                Uploaded {formatTimeAgo(
                                                    asset.uploadedDate
                                                )}
                                            </p>
                                            <p class="text-sm text-gray-300">
                                                {bytesToFileSize(
                                                    asset.fileSize
                                                )}
                                            </p>
                                            <p
                                                class="my-2 text-sm text-gray-300">
                                                {$t('viewImage.resolution', {
                                                    values: { resolution },
                                                })}
                                            </p>

                                            <div
                                                class="my-4 flex flex-row gap-2">
                                                <a
                                                    href="https://v2-api-testing.wanderer.moe/download/{asset.id}"
                                                    rel="noreferrer"
                                                    target="_blank"
                                                    download>
                                                    <button
                                                        class="btn px-2.5 py-1 font-semibold transition">
                                                        <i
                                                            class="fa-solid fa-download mr-1"
                                                        ></i> Download Asset
                                                    </button>
                                                </a>
                                                <button
                                                    class="btn px-2.5 py-1 font-semibold transition"
                                                    on:click="{() => {
                                                        navigator.clipboard.writeText(
                                                            window.location.href
                                                        )
                                                    }}">
                                                    <i
                                                        class="fa-solid fa-clipboard mr-1"
                                                    ></i> Copy Link
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="my-4">
                        <p class="my-2 text-2xl text-white">Similar Assets</p>
                        <div
                            class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
                            {#each similarAssets as similarAsset}
                                <AssetItem asset="{similarAsset}" />
                            {/each}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// src/app/asset/[id]/page.tsx
import AssetContainer from '@/components/asset/assetsContainer'
import SkeletonLoader from '@/components/placeholders/skeletonLoader'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableRow,
} from '@/components/ui/table'
import { Asset, SimilarAsset } from '@/interfaces/asset'
import { bytesToFileSize } from '@/lib/helpers/asset/bytesToFileSize'
import { mapAssetType, mapGame } from '@/lib/helpers/casing/mapping'
import {
    Boxes,
    ChevronRightCircle,
    Copy,
    Download,
    Image,
    Info,
} from 'lucide-react'
import { Metadata } from 'next'
import { notFound } from 'next/navigation'

async function getAsset(
    id: string,
): Promise<{ asset: Asset; similarAssets: SimilarAsset[] }> {
    const res = await fetch(`https://v2-api-testing.wanderer.moe/asset/${id}`)
    const { asset, similarAssets } = await res.json()
    return { asset, similarAssets }
}

type Props = {
    params: { id: string }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { id } = params
    const { asset } = await getAsset(id)

    if (!asset) return notFound()

    return {
        title: `${asset.name} (${mapGame(asset.game)}: ${mapAssetType(
            asset.asset_category,
        )}) - wanderer.moe`,
        description: `Information about ${asset.name} from ${mapGame(
            asset.game,
        )} - ${mapAssetType(asset.asset_category)}`,
    }
}

async function AssetPage({ params: { id } }: { params: { id: string } }) {
    const { asset, similarAssets } = await getAsset(id)
    const assetName = asset.name.split('.').shift()
    const assetFormat = asset.name.split('.').pop()

    return (
        <main className="mx-auto min-h-screen max-w-screen-xl p-5">
            {asset ? (
                <>
                    {/* TODO: Add a breadcrumb here :) */}
                    <div className="mb-4 grid grid-cols-1 gap-4 lg:grid-cols-2">
                        <div className="relative items-center justify-center rounded-xl border bg-secondary/25">
                            <h1 className="flex items-center justify-center gap-2 rounded-t-xl border-b bg-background py-2 text-base">
                                <Image size={16} /> Asset
                            </h1>
                            <div className="flex h-[425px] items-center justify-center p-4">
                                <img
                                    src={`https://cdn.wanderer.moe/${asset.url}`}
                                    alt={assetName}
                                    className="checkerboard max-h-full rounded-lg border object-contain object-left shadow-lg"
                                />
                            </div>
                        </div>
                        <div className="overflow-y-auto rounded-xl border bg-secondary/25">
                            <h1 className="flex items-center justify-center gap-2 rounded-t-xl border-b bg-background py-2 text-base">
                                <Info size={16} /> Asset Information
                            </h1>
                            <Table>
                                <TableBody>
                                    <TableRow>
                                        <TableHead>Name</TableHead>
                                        <TableCell colSpan={3}>
                                            {assetName}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Game</TableHead>
                                        <TableCell colSpan={3}>
                                            <div className="flex items-center">
                                                <img
                                                    src={`https://cdn.wanderer.moe/${asset.game}/icon.png`}
                                                    className="mr-2 h-4 w-4 rounded"
                                                    alt={asset.game}
                                                />
                                                {mapGame(asset.game)}
                                            </div>
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Asset Category</TableHead>
                                        <TableCell colSpan={3}>
                                            {mapAssetType(asset.asset_category)}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Tags</TableHead>
                                        <TableCell colSpan={3}>
                                            {asset.tags
                                                .split(',')
                                                .map((tag) => (
                                                    <Badge
                                                        key={tag}
                                                        variant="outline">
                                                        {tag}
                                                    </Badge>
                                                ))}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Status</TableHead>
                                        <TableCell colSpan={3}>
                                            {/* TODO: Add semantic colors here */}
                                            <Badge variant="outline">
                                                {asset.status}
                                            </Badge>
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Uploaded By</TableHead>
                                        <TableCell colSpan={3}>
                                            {asset.uploaded_by}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow>
                                        <TableHead>Uploaded Date</TableHead>
                                        <TableCell>
                                            {new Date(
                                                asset.uploaded_date,
                                            ).toLocaleString()}
                                        </TableCell>
                                        <TableHead className="hidden sm:table-cell">
                                            File Size
                                        </TableHead>
                                        <TableCell className="hidden sm:table-cell">
                                            {bytesToFileSize(asset.file_size)}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow className="border-0">
                                        <TableHead className="hidden sm:table-cell">
                                            Resolution
                                        </TableHead>
                                        <TableCell className="hidden sm:table-cell">
                                            PLACEHOLDER
                                        </TableCell>
                                        <TableHead className="hidden sm:table-cell">
                                            File Type
                                        </TableHead>
                                        <TableCell className="hidden uppercase sm:table-cell">
                                            {assetFormat}
                                        </TableCell>
                                    </TableRow>
                                    <TableRow className="sm:hidden">
                                        <TableHead>File Size</TableHead>
                                        <TableCell>
                                            {bytesToFileSize(asset.file_size)}
                                        </TableCell>
                                    </TableRow>
                                    {/* TODO: Implement */}
                                    <TableRow className="sm:hidden">
                                        <TableHead>Resolution</TableHead>
                                        <TableCell>PLACEHOLDER</TableCell>
                                    </TableRow>
                                    <TableRow className="sm:hidden">
                                        <TableHead>File Type</TableHead>
                                        <TableCell className="uppercase">
                                            {assetFormat}
                                        </TableCell>
                                    </TableRow>
                                </TableBody>
                            </Table>
                        </div>
                    </div>
                    <div className="mt-4 flex w-full flex-col gap-4 sm:flex-row">
                        {/* TODO: Implement */}
                        <Button
                            variant="outline"
                            className="w-full"
                            title="Download Image">
                            <Download size={16} />
                        </Button>
                        <Button
                            variant="outline"
                            className="w-full"
                            title="Copy Image">
                            <Copy size={16} />
                        </Button>
                        <Button
                            variant="outline"
                            className="w-full"
                            title="Add to Collection">
                            <Boxes size={16} />
                        </Button>
                    </div>
                    {similarAssets.length > 0 && (
                        <>
                            <div className="mt-4 rounded-xl border bg-secondary/25">
                                <h1 className="flex items-center justify-center gap-2 rounded-t-xl border-b bg-background py-2 text-base">
                                    <ChevronRightCircle size={16} /> Similar
                                    Assets
                                </h1>
                                <div className="p-4">
                                    <AssetContainer
                                        assets={similarAssets}
                                        displayCounter={false}
                                    />
                                </div>
                            </div>
                        </>
                    )}
                </>
            ) : (
                <div className="flex flex-col items-center justify-center">
                    <SkeletonLoader />
                </div>
            )}
        </main>
    )
}

export default AssetPage
