// src/components/GameContainer.svelte
<script lang="ts">
import { fixCasing } from '@/lib/helpers/casing/fixCasing'
import { formatTimeAgo } from '@/lib/helpers/timeConvertion/isoFormat'
export let game
export let focusedImage
export let handleImageChange
</script>

<a href="/{game.name}">
    <div
        class="relative flex h-40 items-center justify-center overflow-hidden rounded-md bg-cover text-white transition ease-in-out hover:scale-105"
        style="background-image: url('https://cdn.wanderer.moe/{game.name}/cover.png'); background-position: 50% 20%;"
        on:mouseover="{() => {
            if (focusedImage !== game.name) {
                handleImageChange(game.name)
            }
        }}"
        on:focus="{() => {
            if (focusedImage !== game.name) {
                handleImageChange(game.name)
            }
        }}">
        <div
            class="absolute inset-0 bg-gradient-to-t from-black/70 via-black/60 to-black/50">
        </div>
        <div class="align-center absolute">
            <p class="mt-2 text-center text-3xl font-bold text-white">
                {fixCasing(game.name)}
            </p>
            <p class="text-center text-white">
                Updated {formatTimeAgo(game.lastUploaded)}
            </p>
        </div>
    </div>
</a>

// src/components/game/gameContainer.tsx
import Link from 'next/link'
import { mapGame, mapAssetType } from '@/lib/helpers/casing/mapping'
import { useState } from 'react'
import { motion } from 'framer-motion'

export default function GameContainer(game: any) {
    const [hovered, setHovered] = useState<boolean>(false)

    return (
        <Link href={`/search?game=${game.name}`}>
            <div
                onMouseEnter={() => setHovered(true)}
                onMouseLeave={() => setHovered(false)}>
                <motion.div
                    className="relative flex h-32 items-center justify-center bg-cover text-white"
                    style={{
                        backgroundImage: `url(https://cdn.wanderer.moe/${game.name}/cover.png)`,
                        backgroundPosition: '50% 20%',
                        backgroundSize: '100%',
                    }}
                    animate={{
                        // idk about this, will probably change
                        backgroundSize: hovered ? '115%' : '100%',
                        backgroundPosition: hovered ? '50% 15%' : '50% 20%',
                    }}
                    transition={{ duration: 0.15 }}>
                    <motion.div
                        className="absolute h-full w-full bg-black bg-opacity-60"
                        animate={{
                            opacity: hovered ? 0.9 : 1,
                        }}
                        transition={{ duration: 0.15 }}
                    />
                    <div className="align-center absolute">
                        <motion.p
                            className="text-center text-2xl font-bold text-white"
                            animate={{
                                opacity: hovered ? 1 : 1,
                                y: hovered ? 0 : 10,
                            }}
                            transition={{ duration: 0.15 }}>
                            {mapGame(game.name)}
                        </motion.p>
                        <motion.p
                            className="text-center text-white"
                            animate={{
                                opacity: hovered ? 1 : 0,
                                y: hovered ? 0 : 10,
                            }}
                            transition={{ duration: 0.15 }}>
                            {game.assetCategories.length}{' '}
                            {game.assetCategories.length === 1
                                ? 'category'
                                : 'categories'}{' '}
                            available
                        </motion.p>
                    </div>
                </motion.div>
            </div>
        </Link>
    )
}
