// src/components/asset/assetItem.tsx
/* eslint-disable @next/next/no-img-element */
'use client'

import Link from 'next/link'
import { Asset } from '@/interfaces/asset'
import { mapGame, mapAssetType } from '@/lib/helpers/casing/mapping'
import {
    Card,
    CardTitle,
    CardDescription,
    CardHeader,
    CardContent,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { HardDriveDownload, ExternalLink } from 'lucide-react'
import { bytesToFileSize } from '@/lib/helpers/asset/bytesToFileSize'
import { timeAgo } from '@/lib/helpers/time'

export default function AssetItem(asset: Asset) {
    return (
        <div>
            <Card className="p-2 transition-all hover:cursor-pointer hover:bg-zinc-400/5">
                <div className="relative flex items-center">
                    <div className="mr-4 flex-shrink-0 justify-center rounded-lg bg-zinc-800/20 p-1">
                        <img
                            src={`https://cdn.wanderer.moe/${asset.url}`}
                            className="max-w-32 h-32 max-h-32 w-32 object-contain object-left"
                            alt={asset.name}
                        />
                    </div>
                    <div>
                        <div className="flex flex-row gap-1">
                            <Link href={`/search?game=${asset.game}`}>
                                <Button
                                    variant="outline"
                                    size="cs"
                                    className="text-xs font-normal">
                                    <img
                                        src={`https://cdn.wanderer.moe/${asset.game}/icon.png`}
                                        className="h-4 w-4"
                                        alt={asset.game}
                                    />
                                </Button>
                            </Link>
                            <Link
                                href={`/search?asset=${asset.asset_category}`}>
                                <Button
                                    variant="outline"
                                    size="cs"
                                    className="text-xs font-normal">
                                    {mapAssetType(asset.asset_category)}
                                </Button>
                            </Link>
                        </div>
                        <p className="font-normal">{asset.name}</p>
                        <p className="text-xs font-normal">
                            Size: {bytesToFileSize(asset.file_size)}
                        </p>
                        <p className="text-xs font-normal">
                            Uploaded {timeAgo(asset.uploaded_date)}
                        </p>
                        <div className="flex flex-row gap-2">
                            <Link
                                href={`https://v2-api-testing.wanderer.moe/download/${asset.id}`}>
                                <Button size="sm" className="mt-2 text-sm">
                                    <HardDriveDownload className="mr-2 h-4 w-4" />
                                    Download
                                </Button>
                            </Link>
                            <Link href={`/asset/${asset.id}`}>
                                <Button size="sm" className="mt-2 text-sm">
                                    <ExternalLink className="mr-2 h-4 w-4" />
                                    View
                                </Button>
                            </Link>
                        </div>
                    </div>
                </div>
            </Card>
        </div>
    )
}

// src/components/AssetItem.svelte
<script lang="ts">
import { bytesToFileSize } from '@/lib/helpers/asset/bytesToFileSize'
import { formatTimeAgo } from '@/lib/helpers/timeConvertion/isoFormat'
import Lazy from 'svelte-lazy'
import type { Asset } from '@/lib/types/asset'
import { t } from 'svelte-i18n'
import LoadPlaceHolder from './LoadPlaceHolder.svelte'
import { fixCasing } from '@/lib/helpers/casing/fixCasing'
import { mapGame, mapAssetType } from '@/lib/helpers/casing/gameMapping'

export let asset: Asset
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
    role="button"
    tabindex="0"
    class="relative flex transform cursor-pointer items-center rounded-md border-[3px] border-main-500 bg-main-500 p-3 font-semibold text-gray-400 transition duration-150 hover:-translate-y-1 hover:border-main-300">
    <Lazy
        height="{128}"
        placeholder="{LoadPlaceHolder}"
        fadeOption="{{
            delay: 100,
            duration: 1000,
        }}">
        <img
            id="assetimg"
            class="max-w-28 h-28 max-h-28 w-28 object-contain object-left p-1"
            src="{asset.url}"
            alt="{asset.name}" />
    </Lazy>
    <div class="p-2">
        <div class="whitespace-normal break-all">
            <div class="flex flex-row gap-y-2 text-xs">
                <div>
                    <span
                        class="rounded-md bg-main-400 px-2.5 py-1 text-xs font-semibold text-white">
                        <img
                            src="https://cdn.wanderer.moe/{asset.game}/icon.png"
                            alt="{asset.game} cover"
                            class="mr-1 inline-block h-4 w-4 rounded-md" />
                        {mapGame(asset.game)}
                    </span>
                    <span
                        class="rounded-md bg-main-400 px-2.5 py-1 text-xs font-semibold text-white">
                        {mapAssetType(asset.asset)}
                    </span>
                </div>
            </div>
            <div class="my-3">
                <p class="overflow-clip font-semibold lowercase text-white">
                    {asset.name.replace('.png', '')}
                </p>
                <p class="text-xs">
                    Uploaded {formatTimeAgo(asset.uploadedDate)}
                </p>
                <p class="text-xs">
                    {bytesToFileSize(asset.fileSize)}
                </p>
            </div>
            <div class="flex gap-2">
                <a
                    href="https://v2-api-testing.wanderer.moe/download/{asset.id}"
                    rel="noreferrer"
                    target="_blank"
                    download>
                    <button
                        class="btn w-full px-2.5 py-1 font-semibold transition md:w-auto">
                        <i class="fa-solid fa-download mr-1"></i> Download
                    </button>
                </a>
                <a href="/asset/{asset.id}" rel="external">
                    <button
                        class="btn w-full px-2.5 py-1 font-semibold transition md:w-auto">
                        <i class="fa-solid fa-external-link mr-1"></i> View Details
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
