// src/components/ScrollToTop.svelte
<script>
import { onMount } from 'svelte'
import { fade } from 'svelte/transition'

let buttonVisible = false

onMount(() => {
    window.addEventListener('scroll', () => {
        if (window.scrollY > 500) {
            buttonVisible = true
        } else {
            buttonVisible = false
        }
    })
})

function scrollToTop() {
    window.scrollTo({
        top: 0,
        behavior: 'smooth',
    })
}
</script>

{#if buttonVisible}
    <div
        class="fixed bottom-0 right-0 z-50 mb-9 mr-7"
        in:fade="{{ duration: 150 }}"
        out:fade="{{ duration: 150 }}">
        <button
            class="rounded-full bg-main-600 bg-opacity-70 p-2 px-3 py-2 font-bold text-white backdrop-blur-lg backdrop-filter transition-all hover:bg-main-700"
            on:click="{scrollToTop}">
            <i class="fas fa-chevron-up text-lg"></i>
        </button>
    </div>
{/if}

// src/components/layouts/nav/scrollToTop.tsx
'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { ChevronUp } from 'lucide-react'
import { motion } from 'framer-motion'
import { debounce } from 'lodash'

export function ScrollToTop() {
    const [isVisible, setIsVisible] = useState(false)
    const [isHovered, setIsHovered] = useState(false)

    useEffect(() => {
        const handleScroll = debounce(() => {
            if (window.scrollY > 500) {
                setIsVisible(true)
            } else {
                setIsVisible(false)
            }
        }, 100)

        window.addEventListener('scroll', handleScroll)

        return () => {
            window.removeEventListener('scroll', handleScroll)
        }
    }, [])

    return (
        <motion.div
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            className="fixed bottom-0 right-0 z-50 p-3"
            initial={{ opacity: 0 }}
            animate={{
                opacity: isVisible ? 1 : 0,
                y: isHovered ? -5 : 0,
            }}
            transition={{ duration: 0.15 }}>
            <Button
                variant="outline"
                onClick={() => {
                    window.scrollTo({
                        top: 0,
                        behavior: 'smooth',
                    })
                }}>
                <ChevronUp />
            </Button>
        </motion.div>
    )
}
