// src/components/ScrollToTop.svelte
<script>
import { onMount } from 'svelte'
import { fade } from 'svelte/transition'

let buttonVisible = false

onMount(() => {
    window.addEventListener('scroll', () => {
        if (window.scrollY > 500) {
            buttonVisible = true
        } else {
            buttonVisible = false
        }
    })
})

function scrollToTop() {
    window.scrollTo({
        top: 0,
        behavior: 'smooth',
    })
}
</script>

{#if buttonVisible}
    <div
        class="fixed bottom-0 right-0 z-50 mb-9 mr-7"
        in:fade="{{ duration: 150 }}"
        out:fade="{{ duration: 150 }}">
        <button
            class="rounded-full bg-main-600 bg-opacity-70 p-2 px-3 py-2 font-bold text-white backdrop-blur-lg backdrop-filter transition-all hover:bg-main-700"
            on:click="{scrollToTop}">
            <i class="fas fa-chevron-up text-lg"></i>
        </button>
    </div>
{/if}

// src/components/layouts/nav/scroll-to-top.tsx
'use client'

import { Button } from '@/components/ui/button'
import { motion } from 'framer-motion'
import { debounce } from 'lodash'
import { ChevronUp } from 'lucide-react'
import { useEffect, useState } from 'react'

export function ScrollToTop(): React.ReactElement {
    const [isVisible, setIsVisible] = useState<boolean>(false)
    const [isHovered, setIsHovered] = useState<boolean>(false)

    useEffect(() => {
        const handleScroll = debounce(() => {
            setIsVisible(window.scrollY > 500)
        }, 100)

        window.addEventListener('scroll', handleScroll)

        return () => {
            window.removeEventListener('scroll', handleScroll)
        }
    }, [])

    const handleButtonClick = (): void => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth',
        })
    }

    const handleMouseEnter = (): void => {
        setIsHovered(true)
    }

    const handleMouseLeave = (): void => {
        setIsHovered(false)
    }

    const buttonOpacity: number = isVisible ? 1 : 0
    const buttonY: number = isHovered ? -5 : 0

    return (
        <motion.div
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            className="fixed bottom-0 right-0 z-50 p-3"
            initial={{ opacity: 0 }}
            animate={{
                opacity: buttonOpacity,
                y: buttonY,
            }}
            transition={{ duration: 0.15 }}>
            <Button variant="secondary" onClick={handleButtonClick}>
                <ChevronUp />
            </Button>
        </motion.div>
    )
}
