// src/components/layouts/footer/footer.tsx
import Link from 'next/link'
import { Status } from '@/components/status'
import { Heart } from 'lucide-react'
import { DiscordStatus } from '@/components/discord/discordStatus'

export function SiteFooter() {
    const currentYear = new Date().getFullYear()

    return (
        <footer className="border-t p-3 text-gray-400 backdrop-blur-lg backdrop-filter transition-opacity">
            <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
                <div className="md:flex md:justify-between">
                    <div className="mb-4 flex flex-col md:mb-0">
                        <div className="mt-2 grid gap-2">
                            <Status />
                            <DiscordStatus />
                        </div>
                    </div>
                    <div className="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
                        <div>
                            <p className="mb-4 font-semibold text-white">
                                Socials
                            </p>
                            <ul>
                                <li className="mb-2">
                                    <a
                                        href="https://git.wanderer.moe/"
                                        className="hover:text-white">
                                        GitHub
                                    </a>
                                </li>
                                <li>
                                    <a
                                        href="https://discord.wanderer.moe/"
                                        className="hover:text-white">
                                        Discord Server
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <p className="mb-4 font-semibold text-white">
                                Legal
                            </p>
                            <ul>
                                <li className="mb-2">
                                    <a
                                        href="/legal/privacy-policy"
                                        className="hover:text-white">
                                        Privacy Policy
                                    </a>
                                </li>
                                <li className="mb-2">
                                    <a
                                        href="/legal/terms-of-service"
                                        className="hover:text-white">
                                        Terms of Service
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <p className="mb-4 font-semibold text-white">
                                Other
                            </p>
                            <ul>
                                <li className="mb-2">
                                    <a
                                        href="https://wanderer.moe/asset-request-form"
                                        className="hover:text-white">
                                        Asset Request Form
                                    </a>
                                </li>
                                <li className="mb-2">
                                    <a
                                        href="/contributors"
                                        className="hover:text-white">
                                        Contributors
                                    </a>
                                </li>
                                <li className="mb-2">
                                    <p className="cursor-pointer hover:text-white">
                                        Contribute
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <hr className="border-main-300 my-6 sm:mx-auto lg:my-8" />
                <div className="flex flex-col gap-1 text-center text-xs">
                    <span className="text-white">
                        wanderer.moe © 2022-{currentYear}
                    </span>
                    <span>
                        <p>
                            Not affiliated with any of the games or companies
                            listed on this site unless otherwise stated.
                        </p>
                        <p>
                            Built with{' '}
                            <Heart
                                className="inline-block h-3 w-3 text-gray-400"
                                fill="currentColor"
                            />{' '}
                            using{' '}
                            <Link
                                className="text-white"
                                href="https://nextjs.org/">
                                Next.js
                            </Link>{' '}
                            &{' '}
                            <Link
                                className="text-white"
                                href="https://cloudflare.com/">
                                Cloudflare
                            </Link>{' '}
                            by{' '}
                            <Link
                                className="text-white"
                                href="https://dromzeh.dev/">
                                dromzeh
                            </Link>{' '}
                            and our{' '}
                            <Link className="text-white" href="/contributors">
                                contributors.
                            </Link>
                        </p>
                    </span>
                </div>
            </div>
        </footer>
    )
}

// src/components/nav/Footer.svelte
<script>
import { t } from 'svelte-i18n'
import LocaleDropdown from '@/components/dropdowns/LocaleDropdown.svelte'
import Status from '@/components/Status.svelte'
import Contribute from '@/components/popouts/Contribute.svelte'
const currentYear = new Date().getFullYear()

let contributeOpen = false
</script>

<footer
    class="border-t border-main-300 bg-main-500 bg-opacity-75 p-3 text-gray-400 backdrop-blur-lg backdrop-filter transition-opacity">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a href="/" class="flex items-center gap-1" rel="external"
                    ><img src="/logo.png" alt="logo" class="h-12 w-12" />
                    <span class="text text-xl font-semibold text-white"
                        >wanderer.moe</span
                    ></a>
                <div class="mt-2 grid gap-2">
                    <Status />
                    <LocaleDropdown />
                </div>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
                <div>
                    <p class="mb-6 font-semibold text-white">Socials</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="https://git.wanderer.moe/"
                                class="hover:font-semibold hover:text-white"
                                >GitHub</a>
                        </li>
                        <li>
                            <a
                                href="https://discord.wanderer.moe/"
                                class="hover:font-semibold hover:text-white"
                                >Discord Server</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="mb-6 font-semibold text-white">Legal</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="/privacy-policy"
                                class="hover:font-semibold hover:text-white"
                                >Privacy Policy</a>
                        </li>
                        <li class="mb-4">
                            <a
                                href="/terms-of-service"
                                class="hover:font-semibold hover:text-white"
                                >Terms of Service</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="mb-6 font-semibold text-white">Other</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="https://wanderer.moe/asset-request-form"
                                class="hover:font-semibold hover:text-white"
                                >Asset Request Form</a>
                        </li>
                        <li class="mb-4">
                            <a
                                href="/contributors"
                                class="hover:font-semibold hover:text-white"
                                >Contributors</a>
                        </li>
                        <li class="mb-4">
                            <button
                                on:keypress="{() => (contributeOpen = true)}"
                                on:click="{() => (contributeOpen = true)}"
                                class="cursor-pointer hover:font-semibold hover:text-white">
                                Contribute
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border-main-300 sm:mx-auto lg:my-8" />
        <div class="text-center">
            <div>
                <p class="text-sm">
                    © 2022-{currentYear} — {$t('footer.fanmadeNotice')}
                </p>
                <p class="text-xs">
                    Created with <i class="fas fa-heart text-red-500"></i> by
                    <a
                        href="https://dromzeh.dev/?ref=wanderer.moe"
                        class="hover:font-semibold hover:text-white">dromzeh</a
                    >, powered by
                    <a
                        href="https://cloudflare.com/"
                        class="hover:font-semibold hover:text-white"
                        >Cloudflare</a>
                </p>
            </div>
        </div>
    </div>
</footer>

{#if contributeOpen}
    <Contribute closeContribute="{() => (contributeOpen = false)}" />
{/if}
