// src/components/Footer.svelte
<script>
import { t } from 'svelte-i18n'
import LocaleDropdown from '@/components/LocaleDropdown.svelte'
import Status from '@/components/Status.svelte'
import Contribute from '@/components/Contribute.svelte'
const currentYear = new Date().getFullYear()

let contributeOpen = false
</script>

<footer
    class="border-t border-main-300 bg-main-500 bg-opacity-75 p-3 text-gray-400 backdrop-blur-lg backdrop-filter transition-opacity">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a href="/" class="flex items-center gap-1" rel="external"
                    ><img src="/logo.png" alt="logo" class="h-12 w-12" />
                    <span class="text text-xl font-semibold text-white"
                        >wanderer.moe</span
                    ></a>
                <div class="mt-2 grid gap-2">
                    <LocaleDropdown />
                    <Status />
                </div>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
                <div>
                    <p class="mb-6 font-semibold text-white">Socials</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="https://git.wanderer.moe/"
                                class="hover:font-semibold hover:text-white"
                                >GitHub</a>
                        </li>
                        <li>
                            <a
                                href="https://discord.wanderer.moe/"
                                class="hover:font-semibold hover:text-white"
                                >Discord Server</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="mb-6 font-semibold text-white">Legal</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="/privacy-policy"
                                class="hover:font-semibold hover:text-white"
                                >Privacy Policy</a>
                        </li>
                        <li class="mb-4">
                            <a
                                href="/terms-of-service"
                                class="hover:font-semibold hover:text-white"
                                >Terms of Service</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="mb-6 font-semibold text-white">Other</p>
                    <ul>
                        <li class="mb-4">
                            <a
                                href="https://wanderer.moe/asset-request-form"
                                class="hover:font-semibold hover:text-white"
                                >Asset Request Form</a>
                        </li>
                        <li class="mb-4">
                            <a
                                href="/contributors"
                                class="hover:font-semibold hover:text-white"
                                >Contributors</a>
                        </li>
                        <li class="mb-4">
                            <p
                                on:keypress="{() => (contributeOpen = true)}"
                                on:click="{() => (contributeOpen = true)}"
                                class="cursor-pointer hover:font-semibold hover:text-white">
                                How to Contribute
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border-main-300 sm:mx-auto lg:my-8" />
        <div class="text-center">
            <div>
                <p class="text-sm">
                    © 2022-{currentYear} — {$t('footer.fanmadeNotice')}
                </p>
                <p class="text-xs">
                    Created with <i class="fas fa-heart text-red-500"></i> by
                    <a
                        href="https://dromzeh.dev/?ref=wanderer.moe"
                        class="hover:font-semibold hover:text-white">dromzeh</a
                    >, powered by
                    <a
                        href="https://cloudflare.com/"
                        class="hover:font-semibold hover:text-white"
                        >Cloudflare</a>
                </p>
            </div>
        </div>
    </div>
</footer>

{#if contributeOpen}
    <Contribute closeContribute="{() => (contributeOpen = false)}" />
{/if}

// src/components/nav/footer.tsx
import { DiscordStatus } from "~/components/discord-status";
import { Heart } from "lucide-react";
// import Image from "next/image";
import Link from "next/link";

export function SiteFooter(): React.ReactElement {
    const currentYear = new Date().getFullYear();

    return (
        <footer className="border-t border-border bg-background p-3 text-muted-foreground">
            <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
                <div className="w-full md:flex md:justify-between">
                    <div className="mb-4 flex w-full flex-col md:mb-0 md:w-72">
                        <div className="flex items-center justify-center gap-1 md:justify-start">
                            <img
                                src="/logo.png"
                                alt="wanderer.moe"
                                className=""
                                width={35}
                                height={35}
                            />
                            <Link href="/" passHref>
                                <p className="cursor-pointer text-xl font-semibold text-primary">
                                    wanderer.moe
                                </p>
                            </Link>
                        </div>
                        <div className="mt-4 grid gap-2">
                            <DiscordStatus />
                        </div>
                    </div>
                    <div className="grid grid-cols-2 gap-8 sm:grid-cols-3 sm:gap-6">
                        <div>
                            <p className="mb-4 pt-1 font-semibold text-primary">
                                Socials
                            </p>
                            <ul className="text-muted-foreground">
                                <li className="mb-2">
                                    <Link
                                        href="https://discord.wanderer.moe/"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Discord
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="https://x.com/wanderermoe"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Twitter (X)
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="https://git.wanderer.moe/"
                                        className="transition-colors hover:text-primary"
                                    >
                                        GitHub
                                    </Link>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <p className="mb-4 pt-1 font-semibold text-primary">
                                Other
                            </p>
                            <ul>
                                <li className="mb-2">
                                    <Link
                                        href="/changelog"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Changelog
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="https://status.wanderer.moe/"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Status Page
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="mailto:marcel@wanderer.moe"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Contact
                                    </Link>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <p className="mb-4 pt-1 font-semibold text-primary">
                                Legal
                            </p>
                            <ul>
                                <li className="mb-2">
                                    <Link
                                        href="/privacy-policy"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Privacy Policy
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="mailto:legal@wanderer.moe"
                                        className="transition-colors hover:text-primary"
                                    >
                                        Legal Inquiries
                                    </Link>
                                </li>
                                <li className="mb-2">
                                    <Link
                                        href="mailto:dmca@wanderer.moe"
                                        className="transition-colors hover:text-primary"
                                    >
                                        DMCA Requests
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <hr className="border-main-300 my-6 sm:mx-auto lg:my-8" />
                <div className="flex flex-col gap-1 text-center text-xs">
                    <span className="text-primary font-semibold">
                        wanderer.moe © 2022-{currentYear}
                    </span>
                    <span>
                        <p>
                            Not affiliated with any of the games or companies
                            listed on this site unless otherwise stated.
                        </p>
                        <p>
                            Built with{" "}
                            <Heart
                                className="text-red-300 inline-block h-3 w-3 text-muted-foreground"
                                fill="currentColor"
                            />{" "}
                            by{" "}
                            <Link
                                className="text-primary"
                                href="https://dromzeh.dev/?ref=wanderer.moe"
                            >
                                dromzeh
                            </Link>
                        </p>
                    </span>
                </div>
            </div>
        </footer>
    );
}
